### ISSUE TITLE
Import modification broke the reference

### ISSUE THREAD

**Issue by legaultmarc** [legaultmarc/genometools#8]
``` python
>>> ref.get_sequence("3", 12345667, length=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/gepyto/reference.py", line 211, in get_sequence
    seq = self.ref[chrom][start - 1: end]
  File "/Library/Python/2.7/site-packages/gepyto/reference.py", line 38, in __getitem__
    return self.do_query(key.start + 1, key.stop + 1)
  File "/Library/Python/2.7/site-packages/gepyto/reference.py", line 42, in do_query
    res = db.ensembl.query_ensembl(
AttributeError: 'module' object has no attribute 'ensembl'
```

Should add a test for the reference so this does not happen again and fix the import.

**Comment by legaultmarc** [comment]
This is only on the remote reference...
